name: Run Selenium Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444

    env:
      DISPLAY: :1.0  # Changed display number
      PYTHONPATH: ${{ github.workspace }}  # Ensure PYTHONPATH includes the project root

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.6

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run API Tests
      - name: Run API Tests
        working-directory: api_features
        run: |
          rm -f /tmp/.X1-lock  # Remove the lock file if it exists
          Xvfb :1 -screen 0 1920x1080x16 &
          python -m behave -f behave_html_formatter:HTMLFormatter -o reports/behave_report.html
        continue-on-error: true  # Optional: continue even if tests fail

      # Run UI Tests
      - name: Run UI Tests
        working-directory: ui_features
        run: |
          rm -f /tmp/.X1-lock  # Remove the lock file if it exists
          Xvfb :1 -screen 0 1920x1080x16 &
          python -m behave -f behave_html_formatter:HTMLFormatter -o reports/behave_report.html
        continue-on-error: true  # Optional: continue even if tests fail

      # Upload UI Test Results
      - name: Upload UI Test Results
        uses: actions/upload-artifact@v2
        if: always()  # This ensures that the artifacts are uploaded even if the testing step fails
        with:
          name: ui_features
          path: ui_features/reports/**  # Adjust path according to where your test results are stored

      # Upload API Test Results
      - name: Upload API Test Results
        uses: actions/upload-artifact@v2
        if: always()  # This ensures that the artifacts are uploaded even if the testing step fails
        with:
          name: api_features
          path: api_features/reports/**  # Adjust path according to where your test results are stored